version: '3.5'
services:
    db:
      image: songmai108/mongo-auth:1.0
      environment:
        - AUTH=yes
        - MONGODB_ADMIN_USER=admin
        - MONGODB_ADMIN_PASS=admin123
        - MONGODB_APPLICATION_DATABASE=sample
        - MONGODB_APPLICATION_USER=aashrey
        - MONGODB_APPLICATION_PASS=admin123
      ports:
        - "27017:27017"